//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coronavirus_dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public System.DateTime Data { get; set; }
        public string name { get; set; }
    }
}
